language: python
python:
  - "3.5"
script: make test
notifications:
  email: false
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/incuna_forms'
  matrix:
    - DJANGO='django~=1.9.0'
install:
  - psql -c 'CREATE DATABASE incuna_forms' -U postgres;
  - pip install -r requirements.txt --use-wheel
  - pip install $DJANGO --use-wheel
